import { Strip } from './strip';

export const STRIPS: Strip[] = [
  { id: 0, name: 'L’avant départ', image: 'http://2francaisauquebec.com/imgs/bds/fr/0.jpg' },
  { id: 1, name: 'Arrivée à Montréal', image: 'http://2francaisauquebec.com/imgs/bds/fr/1.jpg' },
  { id: 2, name: 'Trajet vers le Cégep', image: 'http://2francaisauquebec.com/imgs/bds/fr/2.jpg' },
  { id: 3, name: 'Bad Trip au Cégep', image: 'http://2francaisauquebec.com/imgs/bds/fr/3.jpg' },
  { id: 4, name: 'Face Palm', image: 'http://2francaisauquebec.com/imgs/bds/fr/4.jpg' },
  { id: 5, name: 'Semaine d’intégration', image: 'http://2francaisauquebec.com/imgs/bds/fr/5.jpg' },
  { id: 6, name: 'Concert post rentrée scolaire', image: 'http://2francaisauquebec.com/imgs/bds/fr/6.jpg' },
  { id: 7, name: 'Rentrée scolaire difficile', image: 'http://2francaisauquebec.com/imgs/bds/fr/7.jpg' },
  { id: 8, name: 'Remise en question', image: 'http://2francaisauquebec.com/imgs/bds/fr/8.jpg' },
  { id: 9, name: 'Mon nom en québécois', image: 'http://2francaisauquebec.com/imgs/bds/fr/9.jpg' },
  { id: 10, name: 'Changement', image: 'http://2francaisauquebec.com/imgs/bds/fr/10.jpg' },
  { id: 11, name: 'La nourriture', image: 'http://2francaisauquebec.com/imgs/bds/fr/11.jpg' },
  { id: 12, name: 'Tempête solaire', image: 'http://2francaisauquebec.com/imgs/bds/fr/12.jpg' },
  { id: 13, name: 'Oculus Rift', image: 'http://2francaisauquebec.com/imgs/bds/fr/13.jpg' },
  { id: 14, name: 'Vous êtes bizarres, mais je vous aime', image: 'http://2francaisauquebec.com/imgs/bds/fr/14.jpg' },
  { id: 15, name: 'Un week end comme les autres', image: 'http://2francaisauquebec.com/imgs/bds/fr/15.jpg' },
  { id: 16, name: 'Concours de blagues et d\'insultes', image: 'http://2francaisauquebec.com/imgs/bds/fr/16.jpg' },
  { id: 17, name: 'Champion', image: 'http://2francaisauquebec.com/imgs/bds/fr/17.jpg' },
  { id: 18, name: 'Colis', image: 'http://2francaisauquebec.com/imgs/bds/fr/18.jpg' },
  { id: 19, name: 'Miro', image: 'http://2francaisauquebec.com/imgs/bds/fr/19.jpg' },
  { id: 20, name: 'Ninja', image: 'http://2francaisauquebec.com/imgs/bds/fr/20.jpg' },
  { id: 21, name: 'NYC, le trajet', image: 'http://2francaisauquebec.com/imgs/bds/fr/21.jpg' },
  { id: 22, name: 'NYC, premières impressions', image: 'http://2francaisauquebec.com/imgs/bds/fr/22.jpg' },
  { id: 23, name: 'NYC, tourisme et vadrouille', image: 'http://2francaisauquebec.com/imgs/bds/fr/23.jpg' },
  { id: 24, name: 'NYC, les musées', image: 'http://2francaisauquebec.com/imgs/bds/fr/24.jpg' },
  { id: 25, name: 'NYC, l’hôtel', image: 'http://2francaisauquebec.com/imgs/bds/fr/25.jpg' },
  { id: 26, name: 'Acquisition de la basse', image: 'http://2francaisauquebec.com/imgs/bds/fr/26.jpg' },
  { id: 27, name: 'Les cours au Québec', image: 'http://2francaisauquebec.com/imgs/bds/fr/27.jpg' },
  { id: 28, name: 'La conception de Noël', image: 'http://2francaisauquebec.com/imgs/bds/fr/28.jpg' },
  { id: 29, name: 'Le papier bulle', image: 'http://2francaisauquebec.com/imgs/bds/fr/29.jpg' },
  { id: 30, name: 'La coiffeuse', image: 'http://2francaisauquebec.com/imgs/bds/fr/30.jpg' },
  { id: 31, name: 'Loin des yeux loin du coeur', image: 'http://2francaisauquebec.com/imgs/bds/fr/31.jpg' },
  { id: 32, name: 'Le concours de citrouilles', image: 'http://2francaisauquebec.com/imgs/bds/fr/32.jpg' },
  { id: 33, name: 'Hallowween au Québec', image: 'http://2francaisauquebec.com/imgs/bds/fr/33.jpg' },
  { id: 34, name: 'La première neige', image: 'http://2francaisauquebec.com/imgs/bds/fr/34.jpg' },
  { id: 35, name: 'La tasse de lait', image: 'http://2francaisauquebec.com/imgs/bds/fr/35.jpg' }
];
